from . import klump

# {{{ List of codes
KEY_UNKNOWN = klump.SDLK_UNKNOWN
KEY_FIRST = klump.SDLK_FIRST
KEY_BACKSPACE = klump.SDLK_BACKSPACE
KEY_TAB = klump.SDLK_TAB
KEY_CLEAR = klump.SDLK_CLEAR
KEY_RETURN = klump.SDLK_RETURN
KEY_PAUSE = klump.SDLK_PAUSE
KEY_ESCAPE = klump.SDLK_ESCAPE
KEY_SPACE = klump.SDLK_SPACE
KEY_EXCLAIM = klump.SDLK_EXCLAIM
KEY_QUOTEDBL = klump.SDLK_QUOTEDBL
KEY_HASH = klump.SDLK_HASH
KEY_DOLLAR = klump.SDLK_DOLLAR
KEY_AMPERSAND = klump.SDLK_AMPERSAND
KEY_QUOTE = klump.SDLK_QUOTE
KEY_LEFTPAREN = klump.SDLK_LEFTPAREN
KEY_RIGHTPAREN = klump.SDLK_RIGHTPAREN
KEY_ASTERISK = klump.SDLK_ASTERISK
KEY_PLUS = klump.SDLK_PLUS
KEY_COMMA = klump.SDLK_COMMA
KEY_MINUS = klump.SDLK_MINUS
KEY_PERIOD = klump.SDLK_PERIOD
KEY_SLASH = klump.SDLK_SLASH
KEY_0 = klump.SDLK_0
KEY_1 = klump.SDLK_1
KEY_2 = klump.SDLK_2
KEY_3 = klump.SDLK_3
KEY_4 = klump.SDLK_4
KEY_5 = klump.SDLK_5
KEY_6 = klump.SDLK_6
KEY_7 = klump.SDLK_7
KEY_8 = klump.SDLK_8
KEY_9 = klump.SDLK_9
KEY_COLON = klump.SDLK_COLON
KEY_SEMICOLON = klump.SDLK_SEMICOLON
KEY_LESS = klump.SDLK_LESS
KEY_EQUALS = klump.SDLK_EQUALS
KEY_GREATER = klump.SDLK_GREATER
KEY_QUESTION = klump.SDLK_QUESTION
KEY_AT = klump.SDLK_AT
KEY_LEFTBRACKET = klump.SDLK_LEFTBRACKET
KEY_BACKSLASH = klump.SDLK_BACKSLASH
KEY_RIGHTBRACKET = klump.SDLK_RIGHTBRACKET
KEY_CARET = klump.SDLK_CARET
KEY_UNDERSCORE = klump.SDLK_UNDERSCORE
KEY_BACKQUOTE = klump.SDLK_BACKQUOTE
KEY_a = klump.SDLK_a
KEY_b = klump.SDLK_b
KEY_c = klump.SDLK_c
KEY_d = klump.SDLK_d
KEY_e = klump.SDLK_e
KEY_f = klump.SDLK_f
KEY_g = klump.SDLK_g
KEY_h = klump.SDLK_h
KEY_i = klump.SDLK_i
KEY_j = klump.SDLK_j
KEY_k = klump.SDLK_k
KEY_l = klump.SDLK_l
KEY_m = klump.SDLK_m
KEY_n = klump.SDLK_n
KEY_o = klump.SDLK_o
KEY_p = klump.SDLK_p
KEY_q = klump.SDLK_q
KEY_r = klump.SDLK_r
KEY_s = klump.SDLK_s
KEY_t = klump.SDLK_t
KEY_u = klump.SDLK_u
KEY_v = klump.SDLK_v
KEY_w = klump.SDLK_w
KEY_x = klump.SDLK_x
KEY_y = klump.SDLK_y
KEY_z = klump.SDLK_z
KEY_DELETE = klump.SDLK_DELETE
# End of ASCII mapped keysyms

# International keyboard syms
KEY_WORLD_0 = klump.SDLK_WORLD_0
KEY_WORLD_1 = klump.SDLK_WORLD_1
KEY_WORLD_2 = klump.SDLK_WORLD_2
KEY_WORLD_3 = klump.SDLK_WORLD_3
KEY_WORLD_4 = klump.SDLK_WORLD_4
KEY_WORLD_5 = klump.SDLK_WORLD_5
KEY_WORLD_6 = klump.SDLK_WORLD_6
KEY_WORLD_7 = klump.SDLK_WORLD_7
KEY_WORLD_8 = klump.SDLK_WORLD_8
KEY_WORLD_9 = klump.SDLK_WORLD_9
KEY_WORLD_10 = klump.SDLK_WORLD_10
KEY_WORLD_11 = klump.SDLK_WORLD_11
KEY_WORLD_12 = klump.SDLK_WORLD_12
KEY_WORLD_13 = klump.SDLK_WORLD_13
KEY_WORLD_14 = klump.SDLK_WORLD_14
KEY_WORLD_15 = klump.SDLK_WORLD_15
KEY_WORLD_16 = klump.SDLK_WORLD_16
KEY_WORLD_17 = klump.SDLK_WORLD_17
KEY_WORLD_18 = klump.SDLK_WORLD_18
KEY_WORLD_19 = klump.SDLK_WORLD_19
KEY_WORLD_20 = klump.SDLK_WORLD_20
KEY_WORLD_21 = klump.SDLK_WORLD_21
KEY_WORLD_22 = klump.SDLK_WORLD_22
KEY_WORLD_23 = klump.SDLK_WORLD_23
KEY_WORLD_24 = klump.SDLK_WORLD_24
KEY_WORLD_25 = klump.SDLK_WORLD_25
KEY_WORLD_26 = klump.SDLK_WORLD_26
KEY_WORLD_27 = klump.SDLK_WORLD_27
KEY_WORLD_28 = klump.SDLK_WORLD_28
KEY_WORLD_29 = klump.SDLK_WORLD_29
KEY_WORLD_30 = klump.SDLK_WORLD_30
KEY_WORLD_31 = klump.SDLK_WORLD_31
KEY_WORLD_32 = klump.SDLK_WORLD_32
KEY_WORLD_33 = klump.SDLK_WORLD_33
KEY_WORLD_34 = klump.SDLK_WORLD_34
KEY_WORLD_35 = klump.SDLK_WORLD_35
KEY_WORLD_36 = klump.SDLK_WORLD_36
KEY_WORLD_37 = klump.SDLK_WORLD_37
KEY_WORLD_38 = klump.SDLK_WORLD_38
KEY_WORLD_39 = klump.SDLK_WORLD_39
KEY_WORLD_40 = klump.SDLK_WORLD_40
KEY_WORLD_41 = klump.SDLK_WORLD_41
KEY_WORLD_42 = klump.SDLK_WORLD_42
KEY_WORLD_43 = klump.SDLK_WORLD_43
KEY_WORLD_44 = klump.SDLK_WORLD_44
KEY_WORLD_45 = klump.SDLK_WORLD_45
KEY_WORLD_46 = klump.SDLK_WORLD_46
KEY_WORLD_47 = klump.SDLK_WORLD_47
KEY_WORLD_48 = klump.SDLK_WORLD_48
KEY_WORLD_49 = klump.SDLK_WORLD_49
KEY_WORLD_50 = klump.SDLK_WORLD_50
KEY_WORLD_51 = klump.SDLK_WORLD_51
KEY_WORLD_52 = klump.SDLK_WORLD_52
KEY_WORLD_53 = klump.SDLK_WORLD_53
KEY_WORLD_54 = klump.SDLK_WORLD_54
KEY_WORLD_55 = klump.SDLK_WORLD_55
KEY_WORLD_56 = klump.SDLK_WORLD_56
KEY_WORLD_57 = klump.SDLK_WORLD_57
KEY_WORLD_58 = klump.SDLK_WORLD_58
KEY_WORLD_59 = klump.SDLK_WORLD_59
KEY_WORLD_60 = klump.SDLK_WORLD_60
KEY_WORLD_61 = klump.SDLK_WORLD_61
KEY_WORLD_62 = klump.SDLK_WORLD_62
KEY_WORLD_63 = klump.SDLK_WORLD_63
KEY_WORLD_64 = klump.SDLK_WORLD_64
KEY_WORLD_65 = klump.SDLK_WORLD_65
KEY_WORLD_66 = klump.SDLK_WORLD_66
KEY_WORLD_67 = klump.SDLK_WORLD_67
KEY_WORLD_68 = klump.SDLK_WORLD_68
KEY_WORLD_69 = klump.SDLK_WORLD_69
KEY_WORLD_70 = klump.SDLK_WORLD_70
KEY_WORLD_71 = klump.SDLK_WORLD_71
KEY_WORLD_72 = klump.SDLK_WORLD_72
KEY_WORLD_73 = klump.SDLK_WORLD_73
KEY_WORLD_74 = klump.SDLK_WORLD_74
KEY_WORLD_75 = klump.SDLK_WORLD_75
KEY_WORLD_76 = klump.SDLK_WORLD_76
KEY_WORLD_77 = klump.SDLK_WORLD_77
KEY_WORLD_78 = klump.SDLK_WORLD_78
KEY_WORLD_79 = klump.SDLK_WORLD_79
KEY_WORLD_80 = klump.SDLK_WORLD_80
KEY_WORLD_81 = klump.SDLK_WORLD_81
KEY_WORLD_82 = klump.SDLK_WORLD_82
KEY_WORLD_83 = klump.SDLK_WORLD_83
KEY_WORLD_84 = klump.SDLK_WORLD_84
KEY_WORLD_85 = klump.SDLK_WORLD_85
KEY_WORLD_86 = klump.SDLK_WORLD_86
KEY_WORLD_87 = klump.SDLK_WORLD_87
KEY_WORLD_88 = klump.SDLK_WORLD_88
KEY_WORLD_89 = klump.SDLK_WORLD_89
KEY_WORLD_90 = klump.SDLK_WORLD_90
KEY_WORLD_91 = klump.SDLK_WORLD_91
KEY_WORLD_92 = klump.SDLK_WORLD_92
KEY_WORLD_93 = klump.SDLK_WORLD_93
KEY_WORLD_94 = klump.SDLK_WORLD_94
KEY_WORLD_95 = klump.SDLK_WORLD_95

# Numeric keypad
KEY_KP0 = klump.SDLK_KP0
KEY_KP1 = klump.SDLK_KP1
KEY_KP2 = klump.SDLK_KP2
KEY_KP3 = klump.SDLK_KP3
KEY_KP4 = klump.SDLK_KP4
KEY_KP5 = klump.SDLK_KP5
KEY_KP6 = klump.SDLK_KP6
KEY_KP7 = klump.SDLK_KP7
KEY_KP8 = klump.SDLK_KP8
KEY_KP9 = klump.SDLK_KP9
KEY_KP_PERIOD = klump.SDLK_KP_PERIOD
KEY_KP_DIVIDE = klump.SDLK_KP_DIVIDE
KEY_KP_MULTIPLY = klump.SDLK_KP_MULTIPLY
KEY_KP_MINUS = klump.SDLK_KP_MINUS
KEY_KP_PLUS = klump.SDLK_KP_PLUS
KEY_KP_ENTER = klump.SDLK_KP_ENTER
KEY_KP_EQUALS = klump.SDLK_KP_EQUALS

# Arrows + Home/End pad
KEY_UP = klump.SDLK_UP
KEY_DOWN = klump.SDLK_DOWN
KEY_RIGHT = klump.SDLK_RIGHT
KEY_LEFT = klump.SDLK_LEFT
KEY_INSERT = klump.SDLK_INSERT
KEY_HOME = klump.SDLK_HOME
KEY_END = klump.SDLK_END
KEY_PAGEUP = klump.SDLK_PAGEUP
KEY_PAGEDOWN = klump.SDLK_PAGEDOWN

# Function keys
KEY_F1 = klump.SDLK_F1
KEY_F2 = klump.SDLK_F2
KEY_F3 = klump.SDLK_F3
KEY_F4 = klump.SDLK_F4
KEY_F5 = klump.SDLK_F5
KEY_F6 = klump.SDLK_F6
KEY_F7 = klump.SDLK_F7
KEY_F8 = klump.SDLK_F8
KEY_F9 = klump.SDLK_F9
KEY_F10 = klump.SDLK_F10
KEY_F11 = klump.SDLK_F11
KEY_F12 = klump.SDLK_F12
KEY_F13 = klump.SDLK_F13
KEY_F14 = klump.SDLK_F14
KEY_F15 = klump.SDLK_F15

# Key state modifier keys
KEY_NUMLOCK = klump.SDLK_NUMLOCK
KEY_CAPSLOCK = klump.SDLK_CAPSLOCK
KEY_SCROLLOCK = klump.SDLK_SCROLLOCK
KEY_RSHIFT = klump.SDLK_RSHIFT
KEY_LSHIFT = klump.SDLK_LSHIFT
KEY_RCTRL = klump.SDLK_RCTRL
KEY_LCTRL = klump.SDLK_LCTRL
KEY_RALT = klump.SDLK_RALT
KEY_LALT = klump.SDLK_LALT
KEY_RMETA = klump.SDLK_RMETA
KEY_LMETA = klump.SDLK_LMETA
KEY_LSUPER = klump.SDLK_LSUPER # Left "Windows" key
KEY_RSUPER = klump.SDLK_RSUPER # Right "Windows" key
KEY_MODE = klump.SDLK_MODE # "Alt Gr" key
KEY_COMPOSE = klump.SDLK_COMPOSE # Multi-key compose key

# Miscellaneous function keys
KEY_HELP = klump.SDLK_HELP
KEY_PRINT = klump.SDLK_PRINT
KEY_SYSREQ = klump.SDLK_SYSREQ
KEY_BREAK = klump.SDLK_BREAK
KEY_MENU = klump.SDLK_MENU
KEY_POWER = klump.SDLK_POWER # Power Macintosh power key
KEY_EURO = klump.SDLK_EURO # Some european keyboards
KEY_UNDO = klump.SDLK_UNDO # Atari keyboard has Undo

KEY_LAST = klump.SDLK_LAST

# Enumeration of valid key mods (possibly OR'd together)
MOD_NONE = klump.KMOD_NONE
MOD_LSHIFT = klump.KMOD_LSHIFT
MOD_RSHIFT = klump.KMOD_RSHIFT
MOD_LCTRL = klump.KMOD_LCTRL
MOD_RCTRL = klump.KMOD_RCTRL
MOD_LALT = klump.KMOD_LALT
MOD_RALT = klump.KMOD_RALT
MOD_LMETA = klump.KMOD_LMETA
MOD_RMETA = klump.KMOD_RMETA
MOD_NUM = klump.KMOD_NUM
MOD_CAPS = klump.KMOD_CAPS
MOD_MODE = klump.KMOD_MODE
MOD_RESERVED = klump.KMOD_RESERVED
MOD_CTRL = klump.KMOD_CTRL
MOD_SHIFT = klump.KMOD_SHIFT
MOD_ALT = klump.KMOD_ALT
MOD_META = klump.KMOD_META
PRESSED = klump.SDL_PRESSED
RELEASED = klump.SDL_RELEASED
# }}} List of codes

keyname = {code: name for name, code in locals().items() if name.startswith('KEY_')}
handlers = {code: [] for code in keyname.keys()}

def invoke_handlers(key, state):
    for handler in reversed(handlers[key]):
        handler(state)

def handler(key, action):
    '''
    key is one of the above keycodes
    action is a callable, taking one argument - the key state (key.PRESSED or key.RELEASED)
    '''
    handlers[key].append(action)

def process_event(event):
    '''event - a klump.KeyEvent event'''
    invoke_handlers(event.code, event.state)

